### ISSUE TITLE
AppImage for Linux not fully functional (unpacked version works)

### ISSUE THREAD

**Issue by aronsommer** [aronsommer/electron-webview#15]
Setting branch in AppImage on Ubuntu was not working.
Needs more testing...
(unpacked version works)

**Comment by aronsommer** [comment]
Here are some errors I found when running the AppImage via Ubuntu terminal:
Git action:
`git-action exit code: 128`
Setting Git branch:
```
Error: EROFS: read-only file system, open '/tmp/.mount_ElectrRAAALk/resources/settings.json'
    at Object.openSync (node:fs:585:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1800)
    at Object.writeFileSync (node:fs:2153:35)
    at writeNewSettings (/tmp/.mount_ElectrRAAALk/resources/app.asar/main.js:361:6)
    at /tmp/.mount_ElectrRAAALk/resources/app.asar/main.js:654:9 {
  errno: -30,
  syscall: 'open',
  code: 'EROFS',
  path: '/tmp/.mount_ElectrRAAALk/resources/settings.json'
}
```

It seems it has to do with read permissions.
